baseURL = 'https://brucegreer.com/'
languageCode = 'en-us'
title = 'Bruce Greer'
theme = 'brooklyn'

[params]
  description = ''
  storeLink = 'https://store.brucegreer.com'
  tagLine = 'PIANIST - COMPOSER - SONGWRITER - MUSICAL DIRECTOR'
  homeBtnTxt = 'I Make Music'